services:
  smart-bots-mongo:
    env_file: .env
    image: mongo:latest
    container_name: smart-bots-mongo
    command: mongod --port ${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - dbdata6:/data/db
  idea-sparring-bot:
    env_file:
      - .env
      - src/telegram_smart_bots/bots/idea_sparring/.env
    command: poetry run python3 /app/src/telegram_smart_bots/app.py
    volumes:
      - type: bind
        source: src/telegram_smart_bots/logs
        target: /app/src/telegram_smart_bots/logs
    build:
      context: .
      dockerfile: src/telegram_smart_bots/bots/idea_sparring/Dockerfile
    container_name: idea-sparring-bot
    restart: "no"
  voice-journal-bot:
    env_file:
      - .env
      - src/telegram_smart_bots/bots/voice_journal/.env
    command: poetry run python3 /app/src/telegram_smart_bots/app.py
    volumes:
      - type: bind
        source: src/telegram_smart_bots/logs
        target: /app/src/telegram_smart_bots/logs
    build:
      context: .
      dockerfile: src/telegram_smart_bots/bots/voice_journal/Dockerfile
    container_name: voice-journal-bot
    restart: "no"
volumes:
  dbdata6:
