services:
  travel-guru-mongo:
    env_file: .env
    image: mongo:latest
    container_name: travel-guru-mongo
    command: mongod --port ${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - dbdata6:/data/db
  travel-guru-bot:
    env_file: .env
    command: poetry run python3 /app/src/telegram_smart_bots/app.py
    volumes:
      - type: bind
        source: src/telegram_smart_bots/logs
        target: /app/src/telegram_smart_bots/logs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-guru-bot
    restart: "no"
volumes:
  dbdata6:
